function plot_approximationIncrement(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 05-May-2021 17:48:48

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','sigma - m','Color',[0.501960784313725 0.501960784313725 0.501960784313725]);
set(plot1(2),'DisplayName','a - direction vector x');
set(plot1(3),'DisplayName','b - direction vector y');
set(plot1(4),'DisplayName','c - direction vector z');
set(plot1(5),'DisplayName','d - point x');
set(plot1(6),'DisplayName','e - point y');
set(plot1(7),'DisplayName','f - point z');
set(plot1(8),'DisplayName','r - radius');

% Create ylabel
ylabel({'meter'});

% Create xlabel
xlabel({'iteration'});

% Create title
title({'approximation increment'});

box(axes1,'on');
% Create legend
legend(axes1,'show');