function plot_residualsdistribution(data1)
%CREATEFIGURE(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 04-Jun-2021 14:40:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'BinMethod','auto');

% Create ylabel
ylabel({'quantity'});

% Create xlabel
xlabel({'meters'});

% Create title
title({'residuals distribution'});

box(axes1,'on');
